### ISSUE TITLE
Support for Metros

### ISSUE THREAD

**Issue by displague** [equinix/terraform-provider-metal#28]
This issue is a planning/placeholder for incoming work related to backend work in progress:

https://feedback.equinixmetal.com/platform/p/introduce-locations-concept-including-support-for-metros

As information becomes available this description will be updated and comments will be added to support the implementation changes.

Depends on https://github.com/packethost/packngo/issues/238

We wil need a new datasource:
* [x] datasource `metal_metro` #58

We will also need new metro properties. Generally, these will be optional and adjacent to facility. Facility will become optional, when metro is specified. The metro property will be a slug. Users can fetch additional metro details through a lookup on the `metal_metro` datasource.

The following need a read-only metro property:
* [ ] datasource metal_spot_market_request _(Update: request_id is the only parameter, and device_ids the only attribute)_
* [x] datasource metal_spot_market_price metro parameter (make facility optional) #64
* [x] datasource metal_ip_block_ranges metro filter #58
* [x] datasource metal_precreated_ip_block metro property #58
* [ ] datasource metal_volume metro property _(Update: volumes can not be metro scoped)_
* [x] datasource metal_facility metro property #31 #58

The following need an optional metro property as an alternative to the facility. One is required, the values should not conflict, but if they do the API response will handle that - we will not try to prevalidate.

* [x] resource metal_device metro property #46 
* [x] resource metal_spot_market_request  #63 
* [x] resource `metal_vlan` #53 
* [x] resource `reserved_ip_block` #56 

Examples should be broadly be updated to demonstrate metros. A few smaller examples can demonstrate Facilities.

* [x] Examples are updated to use Metros #65
* [x] #36 Examples are updated to use Metro supported plans and images #65

**Comment by displague** [comment]
We wil need a:
* datasource metal_metro
* datasource metal_spot_market_request metro property
* datasource metal_ip_block_ranges metro property
* datasource metal_spot_market_price metro property
* datasource metal_precreated_ip_block metro property
* datasource metal_volume metro property

* resource metal_device metro property (optional and adjacent to facility, behaves in the same way. One of metro of facility is required)
* resource metal_spot_market_request metro property (optional and adjacent to facility, behaves in the same way. One of metro of facility is required)

* resource metal_vlan metro property (optional and adjacent to facility, behaves in the same way. One of metro of facility is required)
* resource reserved_ip_block (optional and adjacent to facility, behaves in the same way. One of metro of facility is required)

**Comment by displague** [comment]
Looking for this to be implemented and merged by April 2.

**Comment by displague** [comment]
All of the checkboxes have been checked. Thanks @t0mk!

For any questions about using metros in this Terraform provider see https://github.com/equinix/terraform-provider-metal/discussions/55
